name: Request Tweet

on:
  workflow_run:
    workflows: ["Deploy Site"]
    types:
      - completed

jobs:
  request:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'ğŸ“ Update Post') }}
    steps:
    - uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ secrets.SEND_REPO }}
        event-type: tweet
